# Generated by Django 4.1.1 on 2022-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="password",
            field=models.CharField(max_length=300),
        ),
    ]
